"use client";

import { useState } from "react";

const sources = [
  ["HelloWorld", "Domaći IT, podrška, prodaja, marketing i QA oglasi sa remote filterom.", "https://www.helloworld.rs/oglasi-za-posao/remote", "Srbija", "Oglasi", "Lokalno"],
  ["Himalayas", "Remote pozicije sa jasnim filterima za Srbiju, iskustvo i tehnologije.", "https://himalayas.app/jobs/countries/serbia", "Srbija", "Oglasi", "Za Srbiju"],
  ["Dynamite Jobs", "Kurirani remote oglasi, uključujući kompanije otvorene za kandidate iz Srbije.", "https://dynamitejobs.com/country/remote-jobs-in-serbia", "Srbija", "Oglasi", "Za Srbiju"],
  ["Remote in Europe", "Kurirani poslovi za evropske vremenske zone u više digitalnih disciplina.", "https://remoteineurope.com/", "Evropa / EMEA", "Oglasi", "EU fokus"],
  ["Remotive", "EMEA kategorija za product, tech, marketing i customer support pozicije.", "https://remotive.com/remote-emea-jobs", "Evropa / EMEA", "Oglasi", "EMEA"],
  ["We Work Remotely", "Jedna od najvećih globalnih baza za poslove koji su u potpunosti remote.", "https://weworkremotely.com/100-percent-remote-jobs", "Globalno", "Oglasi", "Kurirano"],
  ["Wellfound", "Pozicije u međunarodnim startupima za product, razvoj, dizajn i operacije.", "https://wellfound.com/jobs", "Globalno", "Oglasi", "Startupi"],
  ["Upwork", "Globalni freelance projekti iz razvoja, dizajna, marketinga i administracije.", "https://www.upwork.com/freelance-jobs/", "Globalno", "Freelance", "Projekti"],
  ["Contra", "Portfolio-first freelance mreža za kreativne i digitalne profesionalce.", "https://contra.com/features/find-freelance-jobs", "Globalno", "Freelance", "Nezavisno"],
  ["Reactive Resume", "Besplatan open-source alat za uređivanje modernog, izvozivog CV-ja.", "https://rxresu.me/", "Globalno", "Alat", "CV"],
  ["Huntr", "Prati oglase, verzije CV-ja, intervjue, kontakte i sledeće korake.", "https://huntr.co/", "Globalno", "Alat", "Organizacija"],
  ["Jobscan", "Uporedi CV sa konkretnim oglasom, pronađi nedostajuće ATS ključne reči i proveri format.", "https://www.jobscan.co/resume-scanner", "Globalno", "Alat", "ATS CV"],
  ["Interviewing.io", "Anonimne probne tehničke intervjue i AI vežbe za kodiranje, system design i behavior pitanja.", "https://interviewing.io/", "Globalno", "Alat", "Intervju"],
  ["Resume Worded", "Analiza CV-ja i LinkedIn profila sa konkretnim preporukama za jaču prijavu.", "https://resumeworded.com/", "Globalno", "Alat", "CV"],
  ["Built In", "Remote tech oglasi i profili kompanija za razvoj, data, product, dizajn, prodaju i operacije.", "https://builtin.com/jobs/remote", "Globalno", "Oglasi", "Tech"],
  ["Authentic Jobs", "Specijalizovan direktorijum za dizajnere, developere, marketare i kreativne profesionalce.", "https://authenticjobs.com/?search_location=remote", "Globalno", "Oglasi", "Kreativno"],
  ["Behance Jobs", "Freelance i full-time poslovi za vizuelni dizajn, motion, ilustraciju, 3D i kreativnu produkciju.", "https://www.behance.net/joblist", "Globalno", "Oglasi", "Dizajn"],
  ["Freelance Writing", "Oglasi za copywritere, urednike, tehničke pisce i content strategiste, sa filtrima po veštinama.", "https://www.freelancewriting.com/writer-jobs/", "Globalno", "Freelance", "Pisanje"],
  ["JournalismJobs", "Oglasi za reportere, urednike, pisce i dizajnere, uključujući remote i freelance angažmane.", "https://www.journalismjobs.com/job-listings?virtual=3", "Globalno", "Oglasi", "Novinarstvo"],
  ["PowerToFly", "Baza oglasa i karijernih resursa za inkluzivnije zapošljavanje u techu i drugim oblastima.", "https://powertofly.com/jobs", "Globalno", "Oglasi", "Karijera"],
  ["italki", "Postavi cene i termine za online časove jezika uz međunarodnu naplatu i globalnu bazu učenika.", "https://teach.italki.com/", "Globalno", "Freelance", "Podučavanje"],
  ["Twenix", "Online konverzacijski časovi engleskog za odrasle uz materijale i fleksibilne termine.", "https://twenix.com/tweachers-apply/", "Evropa / EMEA", "Freelance", "Podučavanje"],
  ["Lingo Turtle", "Online časovi engleskog za mlade učenike, sa rasporedom koji možeš sam da postaviš.", "https://lingo-turtle.com/", "Srbija", "Freelance", "Podučavanje"],
  ["Joberty", "Istraži IT kompanije, iskustva zaposlenih, intervjue i plate u regionu.", "https://joberty.com/IT-companies?page=1&sort=featured", "Srbija", "Alat", "Istraživanje"],
  ["NCR Voyix Careers", "Zvanične otvorene pozicije kompanije NCR Voyix u Srbiji i inostranstvu.", "https://www.ncrvoyix.com/about/careers", "Srbija", "Oglasi", "Kompanije"],
  ["Poslovi Infostud", "Remote poslovi u IT-u, administraciji, prodaji, podršci i marketingu.", "https://poslovi.infostud.com/remote", "Srbija", "Oglasi", "Lokalno"],
  ["Startuj", "Prakse i početničke pozicije za studente i kandidate na početku karijere.", "https://startuj.infostud.com/prakse", "Srbija", "Oglasi", "Junior"],
  ["Ovde Jobs", "Poslovi za kandidate iz Srbije i regiona kod domaćih i stranih kompanija.", "https://ovdejobs.com/", "Srbija", "Oglasi", "Region"],
  ["Arc", "Remote poslovi i freelance projekti za programere, dizajnere i digitalne profesionalce.", "https://arc.dev/en-rs/remote-jobs", "Srbija", "Oglasi", "Tech"],
  ["Remote Rocketship", "Remote poslovi za Srbiju, od praksi do senior i part-time uloga.", "https://www.remoterocketship.com/country/serbia/jobs/", "Srbija", "Oglasi", "Za Srbiju"],
  ["EU Remote Jobs", "Oglasi u kojima je Srbija eksplicitno navedena kao podržana lokacija.", "https://euremotejobs.com/job-region/serbia/", "Srbija", "Oglasi", "Za Srbiju"],
  ["Remotify Europe", "Evropske kompanije i remote poslovi sa filterom prema državi kandidata.", "https://remotifyeurope.com/remote-jobs?country=Serbia", "Evropa / EMEA", "Oglasi", "EU fokus"],
  ["Working Nomads", "Oglasi razvrstani po oblastima i evropskim vremenskim zonama.", "https://www.workingnomads.com/remote-europe-jobs", "Evropa / EMEA", "Oglasi", "EU fokus"],
  ["Wellfound Europe", "Startup prilike iz IT-a, producta, marketinga, prodaje i operacija u Evropi.", "https://wellfound.com/location/europe", "Evropa / EMEA", "Oglasi", "Startupi"],
  ["NoDesk", "Remote oglasi, direktorijum kompanija i vodiči za rad na daljinu.", "https://nodesk.co/remote-jobs/", "Globalno", "Oglasi", "Kurirano"],
  ["JustRemote", "Globalni remote poslovi iz programiranja, marketinga, pisanja, dizajna i podrške.", "https://justremote.co/remote-jobs/", "Globalno", "Oglasi", "Globalno"],
  ["Jobspresso", "Kurirani oglasi iz IT-a, marketinga, prodaje, dizajna i pisanja.", "https://jobspresso.co/remote-work/", "Globalno", "Oglasi", "Kurirano"],
  ["Remote OK", "Velika globalna baza remote poslova, tehničkih i netehničkih.", "https://remoteok.com/", "Globalno", "Oglasi", "Globalno"],
  ["Remote.com Jobs", "Međunarodni poslovi sa naznačenim dozvoljenim državama i vremenskim zonama.", "https://remote.com/jobs", "Globalno", "Oglasi", "Globalno"],
  ["Startup Jobs", "Otvorene pozicije u startupima širom sveta, uključujući Evropu i EMEA.", "https://startup.jobs/", "Globalno", "Oglasi", "Startupi"],
  ["Freelancer", "Međunarodni freelance projekti iz širokog spektra oblasti.", "https://www.freelancer.com/jobs/", "Globalno", "Freelance", "Projekti"],
  ["Fiverr", "Platforma na kojoj samostalno nudiš digitalne usluge klijentima širom sveta.", "https://www.fiverr.com/", "Globalno", "Freelance", "Usluge"],
  ["PeoplePerHour", "Freelance poslovi iz razvoja, dizajna, pisanja, marketinga i podrške.", "https://www.peopleperhour.com/freelance-jobs", "Globalno", "Freelance", "Projekti"],
  ["Toptal", "Selektivni freelance projekti za iskusne stručnjake u techu, dizajnu i finansijama.", "https://www.toptal.com/talent/apply", "Globalno", "Freelance", "Senior"],
  ["Gun.io", "Ugovorni i freelance angažmani za iskusne programere.", "https://gun.io/", "Globalno", "Freelance", "Tech"],
  ["Dribbble Jobs", "Poslovi za UI/UX, product, web, grafičke i brend dizajnere.", "https://dribbble.com/jobs", "Globalno", "Oglasi", "Dizajn"],
  ["UI/UX Jobs Board", "Remote i freelance oglasi za UI/UX i product dizajnere.", "https://uiuxjobsboard.com/design-jobs/remote", "Globalno", "Oglasi", "Dizajn"],
  ["Content Writing Jobs", "Oglasi za copywritere, tehničke pisce, urednike i autore sadržaja.", "https://contentwritingjobs.com/", "Globalno", "Oglasi", "Pisanje"],
  ["ProBlogger Jobs", "Poslovi za blogere, copywritere, urednike i pisce sadržaja.", "https://problogger.com/jobs/", "Globalno", "Oglasi", "Pisanje"],
  ["Support Driven Jobs", "Oglasi za korisničku podršku i customer success stručnjake.", "https://jobs.supportdriven.com/", "Globalno", "Oglasi", "Podrška"],
  ["Preply", "Kreiraj profil i drži online časove jezika ili drugih predmeta.", "https://preply.com/en/teach", "Globalno", "Freelance", "Podučavanje"],
  ["Cambly", "Online razgovori i časovi engleskog jezika.", "https://www.cambly.com/tutors", "Globalno", "Freelance", "Podučavanje"],
  ["Glassdoor", "Recenzije kompanija, plate, uslovi rada i iskustva sa intervjua.", "https://www.glassdoor.com/Reviews/index.htm", "Globalno", "Alat", "Istraživanje"],
  ["Levels.fyi", "Poređenje plata i ukupnih kompenzacija, naročito za IT uloge.", "https://www.levels.fyi/", "Globalno", "Alat", "Plate"],
  ["Teal", "Prilagođavanje CV-ja, praćenje oglasa i organizovanje procesa zapošljavanja.", "https://www.tealhq.com/", "Globalno", "Alat", "CV"],
  ["Simplify", "Čuvanje oglasa, pomoć pri prijavi i praćenje procesa zapošljavanja.", "https://simplify.jobs/", "Globalno", "Alat", "Organizacija"],
  ["GitLab All-Remote", "Detaljan besplatan priručnik o komunikaciji, dokumentovanju i radu u remote timu.", "https://handbook.gitlab.com/handbook/company/culture/all-remote/", "Globalno", "Alat", "Vodič"],
  ["Good Air Language", "Sveobuhvatna baza i vodič kroz kompanije za online predavanje engleskog jezika, sa detaljima o platama, zahtevima i direktnim linkovima za prijavu.", "https://www.goodairlanguage.com/teaching-english-online-2", "Globalno", "Alat", "ESL vodič"],
  ["Remote.co Blog", "Saveti za traženje posla, intervjue, CV i rad od kuće.", "https://remote.co/blog", "Globalno", "Alat", "Vodič"],
  ["Zapier Remote Guide", "Vodič za produktivnost, alate i organizaciju remote rada.", "https://zapier.com/blog/remote-work/", "Globalno", "Alat", "Vodič"],
  ["Jobgether", "Velika baza verifikovanih remote oglasa sa filtrima po regionu, senioritetu i ugovoru.", "https://jobgether.com/remote-jobs", "Globalno", "Oglasi", "Verifikovano"],
  ["FlexJobs", "Kurirana platforma za remote i fleksibilne poslove, sa naglaskom na proverene oglase.", "https://www.flexjobs.com/remote-jobs", "Globalno", "Oglasi", "Kurirano"],
  ["Virtual Vocations", "Remote oglasi iz razvoja, obrazovanja, pisanja, zdravstva, podrške i administracije.", "https://www.virtualvocations.com/browse", "Globalno", "Oglasi", "Oblasti"],
  ["Welcome to the Jungle", "Oglasi i detaljni profili kompanija za istraživanje tima, kulture i otvorenih pozicija.", "https://www.welcometothejungle.com/en/jobs", "Evropa / EMEA", "Oglasi", "Kompanije"],
  ["Landing.Jobs", "Međunarodne tech pozicije i projekti, uz podršku za remote, hibridni i prekogranični rad.", "https://landing.jobs/jobs", "Evropa / EMEA", "Oglasi", "Tech"],
  ["EURES", "Zvanični evropski portal za oglase, mobilnost, uslove rada i podršku EURES savetnika.", "https://eures.europa.eu/index_en", "Evropa / EMEA", "Oglasi", "EU zvanično"],
  ["European Job Days", "Online evropski događaji za zapošljavanje, oglasi i direktan kontakt sa poslodavcima.", "https://www.europeanjobdays.eu/en", "Evropa / EMEA", "Oglasi", "Događaji"],
  ["Europass", "Zvanični evropski alat za izradu CV-ja, profila veština i prijava za posao.", "https://europass.europa.eu/en", "Evropa / EMEA", "Alat", "CV"],
  ["Work at a Startup", "Zvanična Y Combinator baza remote poslova u najperspektivnijim svetskim startupima.", "https://www.workatastartup.com/", "Globalno", "Oglasi", "Startupi"],
  ["4 Day Week", "Kurirana baza remote poslova sa 4-dnevnom radnom nedeljom (32h) i punom platom.", "https://4dayweek.io/", "Globalno", "Oglasi", "Balans"],
  ["DailyRemote", "Dnevno ažurirani remote oglasi za razvoj, dizajn, marketing, prodaju i podršku.", "https://dailyremote.com/", "Globalno", "Oglasi", "Globalno"],
  ["NativeCamp", "Online časovi engleskog jezika sa fleksibilnim rasporedom 24/7, popularno među predavačima u Srbiji.", "https://nativecamp.net/tutors", "Srbija", "Freelance", "Podučavanje"],
  ["Engoo", "Globalna platforma za online časove engleskog jezika uz obezbeđene nastavne materijale.", "https://teach.engoo.com/", "Globalno", "Freelance", "Podučavanje"],
  ["Outlier", "Plaćeni zadaci za treniranje i evaluaciju AI modela, sa nedeljnim isplatama i podrškom za Srbiju.", "https://outlier.ai/", "Globalno", "Freelance", "AI trening"],
  ["Hubstaff Talent", "Besplatna mreža za direktno povezivanje freelancera i kompanija bez posredničkih provizija.", "https://hubstafftalent.com/", "Globalno", "Freelance", "Bez provizije"],
  ["Frilenseri Poreska", "Zvanični državni portal za samooporezivanje, kalkulator i kvartalnu prijavu prihoda iz inostranstva.", "https://frilenseri.ujp.gov.rs/", "Srbija", "Alat", "Porezi"],
  ["Digitalna Zajednica", "Vodiči, pravni saveti, kalkulatori i podrška za frilensere i preduzetnike u Srbiji.", "https://digitalnazajednica.org/", "Srbija", "Alat", "Zajednica"],
  ["Paušal.rs", "Vodič i platforma za jednostavno vođenje paušalne agencije, fakturisanje i poreske obaveze.", "https://www.pausal.rs/", "Srbija", "Alat", "Paušal"],
  ["Remoters", "Baza remote poslova, digitalnih alata, događaja i vodiča za rad sa bilo koje lokacije.", "https://remoters.net/", "Globalno", "Alat", "Vodič"],
] as const;

const filters = ["Sve", "Srbija", "Evropa / EMEA", "Globalno", "Freelance", "Alat"];

export function LegacyHome() {
  const [filter, setFilter] = useState("Sve");
  const [query, setQuery] = useState("");
  const [saved, setSaved] = useState<string[]>([]);
  const [email, setEmail] = useState("");
  const [subscribed, setSubscribed] = useState(false);
  const matches = sources.filter(([name, description, , region, kind, label]) => (filter === "Sve" || region === filter || kind === filter) && `${name} ${description} ${label}`.toLowerCase().includes(query.toLowerCase()));
  const toggleSaved = (name: string) => setSaved((items) => items.includes(name) ? items.filter((item) => item !== name) : [...items, name]);

  return <main id="top" className="min-h-screen overflow-hidden bg-[#f7f8f4] text-[#17312a]">
    <div className="mx-auto max-w-[1440px] px-5 md:px-10">
      <nav className="flex h-20 items-center justify-between border-b border-[#17312a]/10"><a href="#top" className="flex items-center gap-3 font-semibold"><span className="grid size-9 place-items-center rounded-full bg-[#17312a] text-lg text-[#e9f1de]">r</span>remote<span className="-ml-3 text-[#dc5b38]">put</span></a><div className="hidden gap-7 text-sm font-medium text-[#52675f] md:flex"><a href="#directory">Direktorijum</a><a href="#plan">Plan prijave</a><a href="#tools">Resursi</a></div><a href="#directory" className="rounded-full bg-[#dc5b38] px-4 py-2 text-sm font-semibold text-white">Pronađi posao</a></nav>
      <section className="grid gap-10 py-16 lg:grid-cols-[1.18fr_.82fr] lg:items-end lg:py-24"><div><p className="mb-5 text-xs font-bold tracking-[0.16em] text-[#dc5b38]">● DIREKTAN PUT DO REMOTE KARIJERE</p><h1 className="max-w-4xl font-serif text-5xl leading-[0.98] tracking-[-0.035em] md:text-7xl">Pronađi posao koji radi za tvoj život.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#52675f]">Jedno mirno mesto za oglase dostupne iz Srbije, proveru kompanija i jasne korake od prvog klika do ponude.</p><div className="mt-10 flex flex-wrap gap-7 border-t border-[#17312a]/10 pt-6 text-sm"><div><strong className="block text-2xl">40+</strong><span className="text-[#60736b]">proverenih izvora</span></div><div><strong className="block text-2xl">6</strong><span className="text-[#60736b]">karijernih pravaca</span></div><div><strong className="block text-2xl">1</strong><span className="text-[#60736b]">sistem prijave</span></div></div></div><div className="relative min-h-80 overflow-hidden rounded-lg bg-[#d9e9d6] p-8 md:p-10"><div className="absolute -right-12 -top-16 size-64 rounded-full border-[28px] border-[#e9f1de]" /><div className="relative flex h-full flex-col justify-between"><span className="w-fit rounded-full bg-[#17312a] px-3 py-1 text-xs font-semibold text-[#e9f1de]">ZA KANDIDATE IZ SRBIJE</span><div><p className="max-w-sm font-serif text-3xl leading-tight">Ne šalji CV naslepo. Biraj prilike koje odgovaraju tvojoj lokaciji.</p><a href="#directory" className="mt-6 inline-block font-semibold underline decoration-[#dc5b38] decoration-2 underline-offset-5">Istraži izvore →</a></div></div></div></section>
    </div>
    <section id="directory" className="border-y border-[#17312a]/10 bg-white py-16 md:py-20"><div className="mx-auto max-w-[1440px] px-5 md:px-10"><div className="mb-9 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold tracking-[0.16em] text-[#dc5b38]">DIREKTORIJUM</p><h2 className="mt-2 font-serif text-4xl tracking-[-0.025em] md:text-5xl">Gde vredi gledati</h2></div><p className="max-w-sm text-sm leading-6 text-[#60736b]">Svaki izvor vodi direktno na stranicu za prijavu. Sačuvaj one koji odgovaraju tvom sledećem potezu.</p></div><div className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><label className="flex h-12 max-w-md flex-1 items-center gap-3 rounded-md border border-[#17312a]/15 px-4"><span className="text-lg text-[#60736b]">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent text-sm outline-none placeholder:text-[#8a9891]" placeholder="Pretraži platforme, oblasti, alate..." /></label><div className="flex flex-wrap gap-2">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-3 py-2 text-xs font-semibold transition ${filter === item ? "bg-[#17312a] text-white" : "bg-[#f1f4ef] text-[#52675f]"}`}>{item}</button>)}</div></div><p className="mb-4 text-xs font-medium text-[#60736b]">{matches.length} izvora odgovara pretrazi {saved.length > 0 && `· ${saved.length} sačuvano`}</p><div className="grid gap-x-8 border-t border-[#17312a]/10 md:grid-cols-2 xl:grid-cols-3">{matches.map(([name, description, url, , , label]) => <article key={name} className="group flex min-h-56 flex-col justify-between border-b border-[#17312a]/10 py-6"><div><div className="mb-5 flex items-center justify-between"><span className="rounded-full bg-[#eff4ec] px-2.5 py-1 text-[11px] font-bold text-[#4e665b]">{label}</span><button onClick={() => toggleSaved(name)} aria-label={`Sačuvaj ${name}`} className={`grid size-8 place-items-center rounded-full border ${saved.includes(name) ? "border-[#dc5b38] bg-[#fff1ec] text-[#dc5b38]" : "border-[#17312a]/15 text-[#60736b]"}`}>{saved.includes(name) ? "♥" : "♡"}</button></div><h3 className="text-xl font-semibold">{name}</h3><p className="mt-2 text-sm leading-6 text-[#60736b]">{description}</p></div><a href={url} target="_blank" rel="noreferrer" className="mt-6 w-fit text-sm font-bold group-hover:text-[#dc5b38]">Otvori izvor ↗</a></article>)}</div>{matches.length === 0 && <div className="py-16 text-center text-[#60736b]">Nema rezultata. Probaj drugi pojam ili filter.</div>}</div></section>
    <section id="plan" className="mx-auto max-w-[1440px] px-5 py-20 md:px-10"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold tracking-[0.16em] text-[#dc5b38]">PLAN PRIJAVE</p><h2 className="mt-3 font-serif text-4xl tracking-[-0.025em] md:text-5xl">Mala rutina. Velika razlika.</h2><p className="mt-5 max-w-md leading-7 text-[#60736b]">Napravljen za fokusiranu prijavu, ne za beskonačno skrolovanje oglasa.</p></div><ol className="divide-y divide-[#17312a]/10 border-y border-[#17312a]/10">{[["01", "Uredi svoj signal", "CV prilagodi roli, a LinkedIn naslov jasno reci šta radiš i za koga."], ["02", "Istraži pre prijave", "Proveri kulturu, intervju iskustva i platu preko Joberty, Glassdoor i Levels.fyi."], ["03", "Vodi evidenciju", "Sačuvaj oglas, verziju CV-ja, kontakt i datum sledećeg koraka u jednom trackeru."], ["04", "Vežbaj međunarodno", "Pripremi kratko predstavljanje, konkretne rezultate i pitanja za remote tim."]].map(([number, title, text]) => <li key={number} className="grid grid-cols-[3.5rem_1fr] gap-4 py-6 md:grid-cols-[5rem_1fr]"><span className="font-serif text-2xl text-[#dc5b38]">{number}</span><div><h3 className="text-lg font-bold">{title}</h3><p className="mt-1 leading-6 text-[#60736b]">{text}</p></div></li>)}</ol></div></section>
    <section id="tools" className="bg-[#17312a] py-16 text-[#e9f1de] md:py-20"><div className="mx-auto grid max-w-[1440px] gap-12 px-5 md:px-10 lg:grid-cols-2 lg:items-end"><div><p className="text-xs font-bold tracking-[0.16em] text-[#b8d8bf]">SLEDEĆI KORAK</p><h2 className="mt-3 max-w-xl font-serif text-4xl leading-tight tracking-[-0.025em] md:text-5xl">Nedelja sa jednim dobrim potezom vredi više od sto otvorenih tabova.</h2></div><div><p className="mb-5 max-w-md leading-7 text-[#c7d6ca]">Dobij kratku, korisnu ideju za bolju prijavu i jedan izvor koji ne treba propustiti. Bez buke.</p>{subscribed ? <p className="border-l-2 border-[#dc5b38] pl-4 text-lg font-semibold">Upisano. Vidimo se u sledećem izdanju.</p> : <form onSubmit={(event) => { event.preventDefault(); if (email.trim()) setSubscribed(true); }} className="flex max-w-md gap-2"><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required placeholder="tvoj@email.com" className="h-12 min-w-0 flex-1 rounded-md bg-white px-4 text-sm text-[#17312a] outline-none" /><button className="rounded-md bg-[#dc5b38] px-5 text-sm font-bold text-white">Prijavi me</button></form>}</div></div></section>
    <footer className="bg-[#17312a] px-5 pb-7 text-xs text-[#a8bbb0] md:px-10"><div className="mx-auto flex max-w-[1440px] justify-between border-t border-white/10 pt-6"><span>Remote Put · Srbija i svet</span><span>Ažurirano: avgust 2026.</span></div></footer>
  </main>;
}

const categories = [
  ["Poslovi u Srbiji", "Srbija", "Platforme i kompanije koje zapošljavaju iz Srbije."],
  ["Evropa i EMEA", "Evropa / EMEA", "Remote uloge usklađene sa evropskim zonama."],
  ["Globalni oglasi", "Globalno", "Međunarodne kompanije i startupi."],
  ["Freelance", "Freelance", "Projekti, ugovori i samostalni rad."],
  ["Alati i vodiči", "Alat", "CV, praćenje prijava, plate i priprema."],
] as const;

const resourceGroups = [
  ["Oglasi", "Oglasi za posao", "Platforme, kompanije i baze otvorenih remote pozicija.", "bg-[#edf3eb] text-[#426052]"],
  ["Freelance", "Freelance i ugovorni rad", "Projekti, samostalne usluge i dugoročni angažmani.", "bg-[#f8eee9] text-[#98503a]"],
  ["Alat", "Alati, plate i vodiči", "CV, praćenje prijava, istraživanje kompanija i priprema.", "bg-[#eeeaf6] text-[#5e4f83]"],
] as const;

export default function Home() {
  const [filter, setFilter] = useState("Sve");
  const [query, setQuery] = useState("");
  const [saved, setSaved] = useState<string[]>([]);
  const [showSaved, setShowSaved] = useState(false);
  const matches = sources.filter(([name, description, , region, kind, label]) => {
    const matchesFilter = filter === "Sve" || region === filter || kind === filter;
    const matchesSaved = !showSaved || saved.includes(name);
    return matchesFilter && matchesSaved && `${name} ${description} ${label}`.toLowerCase().includes(query.toLowerCase());
  });
  const groupedMatches = resourceGroups.map(([kind, title, description, color]) => ({
    kind,
    title,
    description,
    color,
    items: matches.filter(([, , , , sourceKind]) => sourceKind === kind),
  })).filter((group) => group.items.length > 0);

  function toggleSaved(name: string) {
    setSaved((items) => items.includes(name) ? items.filter((item) => item !== name) : [...items, name]);
  }

  return <main className="min-h-screen bg-[#f6f7f3] text-[#17312a]">
    <header className="border-b border-[#17312a]/10 bg-[#fdfdfb]"><div className="mx-auto flex h-[74px] max-w-[1540px] items-center justify-between px-5 md:px-12"><a href="#directory" className="flex items-center gap-3 text-sm font-bold"><span className="grid size-9 place-items-center rounded-full bg-[#17312a] text-[#e7f0df]">R</span>Remote poslovi</a><div className="hidden gap-7 text-sm text-[#60736b] md:flex"><a href="#categories">Kategorije</a><a href="#directory">Svi izvori</a></div><button onClick={() => setShowSaved((value) => !value)} className={`rounded-full border px-4 py-2 text-xs font-bold ${showSaved ? "border-[#17312a] bg-[#17312a] text-white" : "border-[#17312a]/15 bg-white"}`}>Sačuvano {saved.length > 0 && `(${saved.length})`}</button></div></header>

    <section className="relative overflow-hidden border-b border-[#17312a]/10 bg-[#e5f0df]"><div className="absolute left-1/2 top-1/2 size-[42rem] -translate-x-1/2 -translate-y-1/2 rounded-full border-[70px] border-[#f5f8ee]" /><div className="relative mx-auto flex min-h-[390px] max-w-[1540px] flex-col items-center justify-center px-5 py-16 text-center md:px-12"><p className="mb-5 rounded-full border border-[#17312a]/15 bg-[#f8fbf4]/90 px-3 py-1.5 text-[11px] font-bold tracking-[0.13em] text-[#4b6658]">REMOTE POSLOVI · SRBIJA · EVROPA · SVET</p><h1 className="max-w-4xl font-serif text-5xl leading-[0.98] tracking-[-0.04em] md:text-7xl">Direktorijum za remote posao</h1><p className="mt-6 max-w-2xl text-base leading-7 text-[#52675f] md:text-lg">Platforme, freelance izvori, kompanije, alati za CV i provera plata. Izaberi kategoriju ili odmah pretraži bazu.</p><a href="#categories" className="mt-9 rounded-full bg-[#17312a] px-6 py-3 text-sm font-bold text-white shadow-sm">Pregledaj kategorije</a></div></section>

    <div className="mx-auto max-w-[1540px] px-5 py-14 md:px-12 md:py-20">
      <section id="categories"><div className="mb-8 flex flex-col items-center text-center"><p className="text-xs font-bold tracking-[0.14em] text-[#dc5b38]">KATEGORIJE</p><h2 className="mt-2 font-serif text-4xl tracking-[-0.03em] md:text-5xl">Izaberi odakle krećeš</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{categories.map(([title, value, description], index) => <button key={value} onClick={() => { setFilter(value); document.getElementById("directory")?.scrollIntoView({ behavior: "smooth" }); }} className={`group min-h-60 rounded-lg border p-7 text-center transition duration-200 ${filter === value ? "border-[#17312a] bg-[#17312a] text-white shadow-lg shadow-[#17312a]/15" : "border-[#17312a]/10 bg-white hover:-translate-y-1 hover:border-[#17312a]/35 hover:shadow-lg hover:shadow-[#17312a]/5"}`}><span className={`mx-auto grid size-11 place-items-center rounded-full text-sm font-bold ${filter === value ? "bg-[#dc5b38] text-white" : "bg-[#e3eee0] text-[#325448]"}`}>0{index + 1}</span><strong className="mt-8 block text-lg">{title}</strong><span className={`mx-auto mt-3 block max-w-[13rem] text-sm leading-6 ${filter === value ? "text-[#c9d8cb]" : "text-[#60736b]"}`}>{description}</span><span className={`mt-7 inline-block text-xs font-bold ${filter === value ? "text-[#e7f0df]" : "text-[#dc5b38]"}`}>Otvori kategoriju →</span></button>)}</div></section>

      <section id="directory" className="mt-20 scroll-mt-8"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-bold tracking-[0.14em] text-[#dc5b38]">PRETRAGA IZVORA</p><h2 className="mt-2 font-serif text-4xl tracking-[-0.03em] md:text-5xl">{filter === "Sve" ? "Svi izvori" : filter}</h2><label className="mx-auto mt-8 flex h-14 max-w-2xl items-center gap-4 rounded-full border border-[#17312a]/15 bg-white px-6 shadow-sm shadow-[#17312a]/5"><span className="text-xl text-[#60736b]">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent text-base outline-none placeholder:text-[#8a9891]" placeholder="Pretraži platformu, oblast ili alat" /></label><div className="mt-6 flex flex-wrap justify-center gap-2">{["Sve", "Srbija", "Evropa / EMEA", "Globalno", "Freelance", "Alat"].map((item) => <button key={item} onClick={() => { setFilter(item); setShowSaved(false); }} className={`rounded-full px-4 py-2 text-xs font-bold ${filter === item ? "bg-[#17312a] text-white" : "border border-[#17312a]/10 bg-white text-[#60736b]"}`}>{item}</button>)}</div><p className="mt-5 text-sm font-medium text-[#60736b]">{matches.length} rezultata {showSaved && "u sačuvanim izvorima"}</p></div>
        <div className="mt-12 space-y-16">{groupedMatches.map((group) => <section key={group.kind} aria-labelledby={`group-${group.kind}`}><div className="mb-6 grid overflow-hidden rounded-lg border border-[#17312a]/10 bg-white md:grid-cols-3"><div className="flex min-h-32 flex-col items-center justify-center border-b border-[#17312a]/10 p-6 text-center md:border-b-0 md:border-r"><span className={`grid size-14 place-items-center rounded-full text-sm font-bold ${group.color}`}>{group.items.length}</span><span className="mt-2 text-xs font-medium text-[#60736b]">izvora u kategoriji</span></div><div className="flex min-h-32 flex-col items-center justify-center border-b border-[#17312a]/10 p-6 text-center md:border-b-0 md:border-r"><p className="text-[11px] font-bold tracking-[0.14em] text-[#dc5b38]">{group.kind.toUpperCase()}</p><h3 id={`group-${group.kind}`} className="mt-2 text-2xl font-semibold tracking-[-0.02em]">{group.title}</h3></div><div className="flex min-h-32 items-center justify-center p-6 text-center"><p className="max-w-xs text-sm leading-6 text-[#60736b]">{group.description}</p></div></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{group.items.map(([name, description, url, region, kind, label]) => <article key={name} role="link" tabIndex={0} onClick={() => window.open(url, "_blank", "noopener,noreferrer")} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") window.open(url, "_blank", "noopener,noreferrer"); }} className="group relative flex min-h-[250px] cursor-pointer flex-col rounded-lg border border-[#17312a]/10 bg-white p-7 transition duration-200 hover:-translate-y-1 hover:border-[#17312a]/30 hover:shadow-xl hover:shadow-[#17312a]/10 focus:outline-none focus:ring-2 focus:ring-[#dc5b38]"><div className="flex items-start justify-between gap-3"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#edf3eb] px-2.5 py-1 text-[10px] font-bold text-[#486256]">{region}</span><span className="rounded-full bg-[#f8eee9] px-2.5 py-1 text-[10px] font-bold text-[#a54931]">{kind}</span></div><button onClick={(event) => { event.stopPropagation(); toggleSaved(name); }} aria-label={`Sačuvaj ${name}`} className={`grid size-9 shrink-0 place-items-center rounded-full border text-base ${saved.includes(name) ? "border-[#dc5b38] bg-[#fff1ec] text-[#dc5b38]" : "border-[#17312a]/15 text-[#60736b] hover:border-[#dc5b38] hover:text-[#dc5b38]"}`}>{saved.includes(name) ? "♥" : "♡"}</button></div><h4 className="mt-7 text-xl font-bold">{name}</h4><p className="mt-3 text-sm leading-6 text-[#60736b]">{description}</p><div className="mt-auto flex items-center justify-between border-t border-[#17312a]/10 pt-5"><span className="text-xs font-medium text-[#7c8c84]">{label}</span><span className="text-sm font-bold text-[#dc5b38]">Otvori izvor ↗</span></div></article>)}</div></section>)}</div>
        {matches.length === 0 && <p className="py-20 text-center text-sm text-[#60736b]">Nema izvora za ovaj filter ili pretragu.</p>}
      </section>
    </div>
    <section className="border-t border-[#17312a]/10 bg-[#e5f0df] px-5 py-14 md:px-12"><div className="mx-auto grid max-w-[1540px] gap-7 text-center md:grid-cols-[1fr_auto] md:items-center md:text-left"><div><p className="text-xs font-bold tracking-[0.14em] text-[#dc5b38]">PREDLOŽI RESURS</p><h2 className="mt-2 font-serif text-3xl tracking-[-0.025em]">Znaš koristan izvor koji nedostaje?</h2><p className="mt-2 text-sm text-[#52675f]">Pošalji link i kratak opis, pa može biti dodat u direktorijum.</p></div><div className="flex flex-wrap justify-center gap-3 md:justify-end"><a href="https://x.com/KoronVirus" target="_blank" rel="noreferrer" className="rounded-full bg-[#17312a] px-5 py-3 text-sm font-bold text-white">Piši na X</a><a href="mailto:zoxknez@hotmail.com?subject=Predlog%20resursa%20za%20Remote%20poslove" className="rounded-full border border-[#17312a]/20 bg-white px-5 py-3 text-sm font-bold text-[#17312a]">Pošalji email</a></div></div></section>
    <footer className="border-t border-[#17312a]/10 bg-white px-5 py-7 text-xs text-[#60736b] md:px-12"><div className="mx-auto flex max-w-[1540px] justify-between"><span>Remote poslovi</span><span>Ažurirano: avgust 2026.</span></div></footer>
  </main>;
}
