import { pageMeta } from "@/lib/seo";
export const metadata=pageMeta("Kako raditi remote iz Srbije","Pregled modela rada: freelancer, preduzetnik, DOO, contractor, zaposlenje i EOR.","/kako-da-radim");
const MODELS=[
["Frilenser","Kvartalno samooporezivanje fizičkog lica za prihode koje domaći isplatilac ne oporezuje po odbitku.","Najmanje administracije, ali pratite rokove i poreski režim."],
["Preduzetnik","Registracija preko APR-a, paušal ili vođenje knjiga u zavisnosti od uslova i delatnosti.","Poslovni status i fakturisanje, uz test samostalnosti i druge obaveze."],
["DOO","Privredno društvo sa punim računovodstvom i odvojenim pravnim subjektivitetom.","Veća administracija i troškovi, često smislenije za kompleksnije poslovanje."],
["Contractor","Ugovor o pružanju usluga bez radnog odnosa.","Ugovor, valuta, rokovi plaćanja, IP i poreske obaveze treba jasno definisati."],
["Direktno zaposlenje","Radni odnos kod poslodavca ili lokalnog entiteta.","Prava i obaveze zavise od ugovora i merodavnog prava."],
["EOR","Treća firma vas formalno zapošljava za stranog klijenta.","Može rešiti lokalno zapošljavanje kada strani poslodavac nema entitet u Srbiji."],
];
export default function Page(){return <main><section className="border-b border-[#17312a]/8 bg-[#eef3ed]"><div className="mx-auto max-w-6xl px-5 py-14 md:px-12 md:py-20"><p className="eyebrow">MODELI RADA</p><h1 className="mt-3 max-w-4xl font-serif text-5xl tracking-[-.04em] md:text-7xl">Šta zapravo znači “radim za strance”?</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#52675f]">Kratko poređenje modela, bez pokušaja da vam aplikacija izabere pravnu ili poresku formu. Za odluku koristite zvanične izvore i stručni savet kada je potreban.</p></div></section><div className="mx-auto max-w-6xl px-5 py-12 md:px-12 md:py-16"><div className="grid gap-4 md:grid-cols-2">{MODELS.map(([title,text,note],i)=><article key={title} className="premium-card p-6"><span className="text-[10px] font-bold tracking-[.13em] text-[#dc5b38]">0{i+1}</span><h2 className="mt-4 font-serif text-3xl">{title}</h2><p className="mt-3 text-sm leading-6 text-[#60736b]">{text}</p><p className="mt-5 rounded-xl bg-[#f6f8f4] p-4 text-xs leading-5 text-[#64746d]">{note}</p></article>)}</div><section className="mt-12 premium-panel p-6"><p className="eyebrow">ZVANIČNO</p><h2 className="mt-2 font-serif text-3xl">Krenite od primarnih izvora</h2><div className="mt-5 flex flex-wrap gap-2"><a href="https://apr.gov.rs/usluge/eservisi/eregistracija-osnivanja-preduzetnika.2406.html" target="_blank" rel="noreferrer" className="chip">APR eRegistracija ↗</a><a href="https://frilenseri.purs.gov.rs/" target="_blank" rel="noreferrer" className="chip">Portal Frilenseri ↗</a><a href="https://purs.gov.rs/e-porezi/portal.html" target="_blank" rel="noreferrer" className="chip">ePorezi ↗</a><a href="https://www.efaktura.gov.rs/" target="_blank" rel="noreferrer" className="chip">eFaktura ↗</a></div></section></div></main>}
