import Link from "next/link";
import { CATEGORY_LABELS, SENIORITY_LABELS } from "@/lib/classify";
import { formatNumberSr } from "@/lib/format";
import { getJobFeed } from "@/lib/jobs/aggregate";
import { annualizeSalary } from "@/lib/salary";
import { pageMeta } from "@/lib/seo";
import type { JobCategory,Seniority } from "@/types";

export const metadata=pageMeta("Plate i javni izvori","Rasponi iz trenutno preuzetih oglasa grupisani po valuti, uz javne salary izvore.","/plate");
export default async function PlatePage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const params=await searchParams;const category=(typeof params.oblast==="string"?params.oblast:"all") as JobCategory|"all";const seniority=(typeof params.senioritet==="string"?params.senioritet:"all") as Seniority|"all";const scope=typeof params.obuhvat==="string"?params.obuhvat:"all";const feed=await getJobFeed().catch(()=>null);
 const jobs=(feed?.jobs??[]).filter(job=>{if(job.salaryMin==null&&job.salaryMax==null)return false;if(category!=="all"&&job.category!==category)return false;if(seniority!=="all"&&job.seniority!==seniority)return false;if(scope==="srbija"&&job.serbiaEligibility!=="CONFIRMED_SERBIA")return false;if(scope==="eu"&&!["EUROPE","EMEA","CONFIRMED_SERBIA"].includes(job.serbiaEligibility))return false;if(scope==="global"&&job.serbiaEligibility!=="WORLDWIDE")return false;return true});
 const grouped=new Map<string,number[]>();for(const job of jobs){const value=job.salaryMax??job.salaryMin;if(value==null||!job.salaryCurrency)continue;const annual=annualizeSalary(value,job.salaryPeriod);if(annual==null)continue;const arr=grouped.get(job.salaryCurrency)??[];arr.push(annual);grouped.set(job.salaryCurrency,arr);}
 const groups=[...grouped.entries()].map(([currency,values])=>({currency,values:values.sort((a,b)=>a-b)}));
 return <main><section className="border-b border-[#17312a]/8 bg-[#f3efe6]"><div className="mx-auto max-w-6xl px-5 py-14 md:px-12 md:py-20"><p className="eyebrow">PLATE</p><h1 className="mt-3 max-w-4xl font-serif text-5xl tracking-[-.04em] md:text-7xl">Rasponi, ne izmišljeni “tržišni prosek”.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#665f50]">Oglasi često koriste različite valute i periode. Zato ih ne sabiramo u jednu besmislenu cifru, već godišnje raspone prikazujemo odvojeno po valuti.</p></div></section><div className="mx-auto max-w-6xl px-5 py-12 md:px-12 md:py-16">
   <form method="get" action="/plate" className="premium-panel grid gap-3 p-5 md:grid-cols-4 md:p-6"><select name="oblast" defaultValue={category} className="premium-field text-sm"><option value="all">Sve uloge</option>{Object.entries(CATEGORY_LABELS).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><select name="senioritet" defaultValue={seniority} className="premium-field text-sm"><option value="all">Sav senioritet</option>{Object.entries(SENIORITY_LABELS).filter(([k])=>k!=="unknown").map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><select name="obuhvat" defaultValue={scope} className="premium-field text-sm"><option value="all">Svi oglasi</option><option value="srbija">Srbija potvrđena</option><option value="eu">EU / EMEA</option><option value="global">Worldwide</option></select><button className="rounded-xl bg-[#17312a] px-4 text-sm font-bold text-white">Primenite filter</button></form>
   <section className="mt-8 grid gap-4 md:grid-cols-2">{groups.length?groups.map(g=><article key={g.currency} className="premium-card p-6"><div className="flex items-center justify-between"><h2 className="font-serif text-3xl">{g.currency}</h2><span className="text-[10px] font-bold text-[#7a8982]">{g.values.length} OGLASA</span></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#f6f7f3] p-4"><p className="text-[10px] font-bold text-[#7a8982]">NAJNIŽI GODIŠNJI</p><strong className="mt-1 block text-xl">{formatNumberSr(g.values[0])} {g.currency}</strong></div><div className="rounded-xl bg-[#f6f7f3] p-4"><p className="text-[10px] font-bold text-[#7a8982]">NAJVIŠI GODIŠNJI</p><strong className="mt-1 block text-xl">{formatNumberSr(g.values[g.values.length-1])} {g.currency}</strong></div></div><p className="mt-4 text-xs leading-5 text-[#7a8982]">Ovo je raspon iz trenutno dostupnih oglasa, ne statistički reprezentativan prosek tržišta.</p></article>):<div className="premium-panel col-span-full p-8 text-sm text-[#60736b]">Nema dovoljno oglasa sa javno objavljenom platom za ovu kombinaciju filtera.</div>}</section>
   <section className="mt-14"><p className="eyebrow">DODATNI IZVORI</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Levels.fyi","https://www.levels.fyi/"],["Glassdoor","https://www.glassdoor.com/Salaries/index.htm"],["HelloWorld","https://www.helloworld.rs/"],["Joberty","https://joberty.com/"]].map(([n,u])=><a key={n} href={u} target="_blank" rel="noreferrer" className="premium-card p-5"><strong>{n}</strong><span className="mt-4 block text-xs text-[#dc5b38]">Otvorite ↗</span></a>)}</div></section>
   <div className="mt-10 rounded-2xl border border-[#dc5b38]/14 bg-[#fff5f0] p-5 text-sm text-[#765f57]"><strong>Eksperimentalno:</strong> rasponi iz live oglasa zavise od kvaliteta i dostupnosti javnih feedova. <Link href="/poslovi?plata=1" className="font-bold text-[#a44931]">Pogledajte oglase sa platom →</Link></div>
 </div></main>
}
